JackalLabs/canine-chain

- vue/src/store/generated/jackal-dao/canine/cosmwasm.wasm.v1/index.ts
- vue/src/store/generated/jackal-dao/canine/cosmwasm.wasm.v1/module/index.ts
- vue/src/store/generated/jackal-dao/canine/jackaldao.canine.rns/index.ts
- vue/src/store/generated/jackal-dao/canine/jackaldao.canine.rns/module/index.ts
- vue/src/store/generated/jackal-dao/canine/jackaldao.canine.storage/index.ts
- vue/src/store/generated/jackal-dao/canine/jackaldao.canine.storage/module/index.ts
Strangely enough, the line 'from := clientCtx.From' inside of tx_add_viewers.go outputs user's name, e.g. 'alice'
However, the same line inside of query_get_keys.go outputs their bech32 address, which caused "query_get_keys" to fail.
Inside of query_get_keys.go I changed the line to: 'from := clientCtx.FromName' and this outputted the user's name, e.g., 'alice'
After this, query_get_keys works.
Intuitively I think this has to do with the fact that clientCtx for a query and clientCtx for a transaction are different 'under the hood', but more learning is required to fully understand.
> get_keys works

- x/filetree/types/merkle-paths.go
Erin Rivas, head of integrations, spotted a necessary fix to merkle-paths.go to enable compatibility with jackal.js. I am submitting this PR on his behalf. 
Best regards,
Bi Phan (on behalf of Erin Rivas)
> Erin fixed merkle

- go.mod
- go.sum
This pull request simply updates ledger-go to v0.9.3 which adds support for Ledger Nano S+.
The same was done in Cosmos Hub a little while back: https://github.com/cosmos/gaia/commit/0420982086799cfad795f1ce271446002b9e5258
The ledger-go v0.9.3 release can be found here to see the changes: https://github.com/cosmos/ledger-go/releases/tag/v0.9.3
> Add support for Ledger Nano S+

- x/storage/abci.go
- x/storage/keeper/common_test.go
- x/storage/keeper/keeper_test.go
- x/storage/keeper/rewards.go
- x/storage/keeper/rewards_test.go
@BiPhan4 can you look this over and run some tests on the reward stuff. We need unit tests on the rewards ASAP.
> remove floating point math

- app/app.go
- app/upgrades/v1.2.0-alpha.6/constant.go
- app/upgrades/v1.2.0-alpha.6/upgrades.go
Added upgrade handler for "Infra & Storage Deals" upgrade, since it was missing in alpha.5. Tested to be running and accepting the upgrade block.
Suggested new version: v1.2.0-alpha.6
> Upgrade handler for "Infra & Storage Deals"

- x/storage/keeper/msg_server_contracts_test.go
- x/storage/keeper/msg_server_sign_contract.go
added check for expiration date
> Fix sign contract

- x/oracle/keeper/keeper_test.go
- x/oracle/keeper/msg_server_feeds_test.go
Added test accounts to [`KeeperTestSuite`](https://github.com/JackalLabs/canine-chain/blob/ece9b3700ad9b8f78cf533af52a2a8f71553a990/x/oracle/keeper/keeper_test.go#L29)
[`reset()`](https://github.com/JackalLabs/canine-chain/blob/ece9b3700ad9b8f78cf533af52a2a8f71553a990/x/oracle/keeper/keeper_test.go#L36) adds three test accounts to `KeeperTestSuite`
Added unit tests for [`CreateFeed()`](https://github.com/JackalLabs/canine-chain/blob/ece9b3700ad9b8f78cf533af52a2a8f71553a990/x/oracle/keeper/msg_server_feeds_test.go#L10) and [`UpdateFeed()`](https://github.com/JackalLabs/canine-chain/blob/ece9b3700ad9b8f78cf533af52a2a8f71553a990/x/oracle/keeper/msg_server_feeds_test.go#L80)
> oracle module unit tests progress update

- go.mod
- go.sum
Now that tendermint is being abandoned by the repo owner, Informal Systems has taken over the core development. As such, Jackal needs to use the new repo as a dependency, see announcement here: https://github.com/tendermint/tendermint/issues/9972
Twitter announcement from informal [here](https://twitter.com/informalinc/status/1613580971592278016).
> switching to informal systems tendermint fork

- x/storage/client/cli/tx.go
- x/storage/client/cli/tx_upgrade_storage.go
- x/storage/keeper/msg_server_upgrade_storage.go
- x/storage/simulation/upgrade_storage.go
There is a miscalculation in storage plan end date. [canine-chain/msg_server_upgrade_storage.go at a39271478a28f936e1c787a736532c89ffe31671 · JackalLabs/canine-chain](https://github.com/JackalLabs/canine-chain/blob/a39271478a28f936e1c787a736532c89ffe31671/x/storage/keeper/msg_server_upgrade_storage.go#L104) 
Month time of type time.Time multiplied with upgrade duration of type time.Duration large enough (like a month) will create integer overflow and result in end date being earlier than current time.
The fix removes timeMonth * timeDuration and End date is calculated as ctx.BlockTime().Add(duration).
> fix upgrade storage plan end date calculation and add upgrade-storage cli cmd

- x/storage/keeper/msg_server_upgrade_storage.go
Added changes to upgrade storage tx.
Upgrade bytes needs to be bigger than current space used.
If the [condition (newBytes < spaceUsed)](https://github.com/JackalLabs/canine-chain/blob/d3f0309e7fd11e3f91cc9e0eaa5da4c3d4118b7c/x/storage/keeper/msg_server_upgrade_storage.go#L64) is true, invalid request error with "cannot downgrade below current usage" is returned.
> add current usage check to storage upgrade tx

- app/app.go
- app/upgrades/recovery/upgrades.go
- scripts/run-upgrade-node.sh
- scripts/upgrade-test.sh
- x/storage/abci.go
- x/storage/keeper/strays.go
Following the initial instability of the Jackal network, there were a couple of providers that shut down and caused some early files to be lost, this has since caused the lost files. There is always the chance that a file is lost forever, this chance is tiny and can only happen when all 3 providers that are storing a file shut down within a short window of time. This is being improved through error-correcting codes in the future. Until then this is the best chance at optimizing an already full "dead files pile". This removes all strays that don't share an FID with an active deal. This will happen once upon upgrading and then once every week following. These weekly purges may cause the block times to be slightly longer for an individual block.
> Feat: Recovery upgrade handler

- x/storage/keeper/msg_server_cancel_contract.go
- x/storage/keeper/msg_server_contracts_test.go
- x/storage/keeper/rewards.go
- x/storage/types/errors.go
Sometimes when cancelling a contract using the cancel contract method, the fid-cid map would be thrown off and keep a dead cid around, this no longer happens and the test suite accurately reflects this.
> Fix: Fid-Cid map properly updates after canceling contract

- scripts/dummy_data/5.svg
- scripts/test-attest-w-upgrade.sh
- x/storage/keeper/msg_server_attest.go
Removes the uncertainty in providers when submitting an attestation and won't kill other attestations when one fails.
> Fix: Attest Always Succeeds

- app/app.go
- app/upgrades/v210/upgrades.go
- x/jklmint/keeper/mint.go
- x/jklmint/keeper/mint_test.go
- x/jklmint/legacy/v210/store.go
- x/jklmint/types/params.go
- x/storage/types/params.go
https://forums.jackalprotocol.com/t/software-upgrade-adjust-storage-provider-rewards/42
> Feat: Provider Rewards to Zero

- x/storage/keeper/msg_server_sign_contract.go
- x/storage/keeper/utils.go
Perpetual storage pricing is now adjusted to use a minimum of 1mb instead of 1gb.
> Perps Rounding to Mbs instead of Gbs

- app/upgrades.go
- app/upgrades/v4/commont_test.go
- app/upgrades/v4/upgrade_test.go
- app/upgrades/v4/upgrades.go
- scripts/upgrade-test.sh
- testutil/context.go
- x/filetree/keeper/common_test.go
- x/notifications/keeper/common_test.go
- x/oracle/keeper/common_test.go
- x/rns/keeper/common_test.go
- x/storage/keeper/common_test.go
- x/storage/keeper/grpc_query_active_deals.go
- x/storage/keeper/grpc_query_active_deals_test.go
- x/storage/keeper/msg_server_attest_test.go
- x/storage/keeper/params.go
- x/storage/keeper/payment_info_test.go
- x/storage/keeper/rewards.go
- x/storage/keeper/utils.go
- x/storage/legacy/v5/store.go
- x/storage/legacy/v5/types.go
Added proper v4 upload handler & tests
> v4 Upgrade Handler

- x/storage/keeper/grpc_query_find_file.go
- x/storage/keeper/rewards.go
Essentially, we were loading ever active deal every time a stray was claimed, now we try to use `fid_cid` mappings to make the lookup faster, and if that for some reason fails, we fall back on loading every active deal. This should improve memory usage A LOT!
> Claim strays using less memory

- .github/workflows/build.yml
- .github/workflows/canary.yml
- .github/workflows/cov.yml
- .github/workflows/golangci.yml
- .github/workflows/release.yml
- .github/workflows/test-full-app-sim.yml
- .github/workflows/test-import-export-sim.yml
- .github/workflows/test-unit.yml
- Makefile
- go.mod
- go.sum
> updating go to 1.22.2

- .golangci.yaml
- x/storage/keeper/grpc_query_find_file.go
fixing find file weirdness maybe?
> adding merkle check to find file

- x/rns/keeper/msg_server_register.go
- x/rns/keeper/names.go
- x/rns/keeper/register_test.go
buying an expired name messes up and you end up paying for time in the past.
> Fixing RNS registration

- x/storage/keeper/grpc_query_active_deals.go
Query by note would fail if it hit a value in the memo that wasn't a string.
> fixing query by note

- x/storage/keeper/msg_server_buy_storage.go
We don't let a ForAddress field be empty but we should, and it should default to the sender.
> Empty ForAddress when buying storage

- x/storage/keeper/proofs.go
- x/storage/keeper/providers.go
As of late, some webapps I've been working on are struggling to initialize when querying a list of all active providers. This often leads to a gateway timeout, internal server error, among other issues.
This was due to the sheer number of proofs that exist now as we approach 100k files stored. Here's a small patch to avoid the problem alltogether.
I used Haruka Nodes on mainnet to test these changes. Initially, via an gRPC query it took up to 3 minutes to respond to the request for ActiveProviders. Attempts with RPC endpoints (Jackal internalrpc, Brochain, Mathnodes, Stavr) have led to similar results, often timing out around 40s.
After the changes were implemented, my gRPC query responded in 523ms and delivered the same result.
Cheers 🍻
> make GetAllActiveProviders more efficient
