JackalLabs/canine-chain

- x/filetree/README.md
- x/filetree/types/merkle-paths.go
Added merkle paths & filetree merkle path docs
> Merkle path

- cmd/canined/http.go
- cmd/canined/types.go
- vue/src/store/generated/jackal-dao/canine/cosmwasm.wasm.v1/index.ts
- vue/src/store/generated/jackal-dao/canine/cosmwasm.wasm.v1/module/index.ts
- vue/src/store/generated/jackal-dao/canine/jackaldao.canine.dsig/index.ts
- vue/src/store/generated/jackal-dao/canine/jackaldao.canine.dsig/module/index.ts
- vue/src/store/generated/jackal-dao/canine/jackaldao.canine.filetree/index.ts
- vue/src/store/generated/jackal-dao/canine/jackaldao.canine.filetree/module/index.ts
- vue/src/store/generated/jackal-dao/canine/jackaldao.canine.rns/index.ts
- vue/src/store/generated/jackal-dao/canine/jackaldao.canine.rns/module/index.ts
- vue/src/store/generated/jackal-dao/canine/jackaldao.canine.storage/index.ts
- vue/src/store/generated/jackal-dao/canine/jackaldao.canine.storage/module/index.ts
`http://0.0.0.0:3333/list` or `http://0.0.0.0:3333/l` will now list all file ids stored on the providers
> Added list-files to provider API

- x/storage/keeper/grpc_query_find_file.go
findFile now returns valid JSON as response
> Json provider ip

- .github/workflows/build.yml
Working on the CICD side of things and we get this brutalized yml script for github actions. My favourite part is I had to test it by making commits! Anyways just push a tag to master and it'll release for you :)
> Adding automated releases on tags being pushed

- cmd/canined/file_server.go
- cmd/canined/queue.go
- cmd/canined/types.go
Quick fix to get error codes in the queue response
> status codes are effective now

- app/app.go
- app/upgrades/v2/constant.go
- app/upgrades/v2/upgrades.go
@faddat This is my first time dealing with Upgrades, can you confirm this is correct? Thx
Used Evmos, Juno, and Cosmos docs as reference
AFAIK we can't set StoreKeys = nil since the modules were removed entirely
Closes out #74 Plan
> Add UpgradeHandler to remove old modules

- scripts/multinode-local-testnet.sh
> Updating scripts

- x/storage/keeper/msg_server_buy_storage.go
- x/storage/keeper/msg_server_buy_storage_test.go
👋 go test -v -run TestStorageTestSuite/TestBuyStorage
> added test for msg_server_buy_storage

- x/storage/keeper/msg_server_proofs_test.go
`go test -v -run TestStorageTestSuite/TestPostProof`
Let me know if this needs more test cases or any adjustment.
> Jkl 136 msg server proofs test go

- x/filetree/keeper/access_test.go
- x/filetree/types/message_add_editors.go
- x/filetree/types/message_add_viewers.go
- x/filetree/types/message_change_owner.go
- x/filetree/types/message_delete_file.go
- x/filetree/types/message_make_root.go
- x/filetree/types/message_post_file.go
- x/filetree/types/message_postkey.go
- x/filetree/types/message_remove_editors.go
- x/filetree/types/message_remove_viewers.go
- x/filetree/types/message_reset_editors.go
- x/filetree/types/message_reset_viewers.go
added tests to all functions at access.go in filetree module
> Jkl 144 unit testing access go

- x/filetree/keeper/access.go
- x/filetree/keeper/access_test.go
- x/filetree/keeper/msg_server_add_viewers_test.go
- x/filetree/keeper/msg_server_delete_file_test.go
- x/filetree/keeper/msg_server_remove_viewers_test.go
- x/filetree/types/test_helpers.go
Branched off from JKL-158. Linted and Tested locally. All good.
> remove viewers test done -- wrong description for commit 

- proto/canine_chain/rns/query.proto
- x/rns/keeper/grpc_query_bids.go
- x/rns/keeper/grpc_query_forsale.go
- x/rns/keeper/grpc_query_init.go
- x/rns/keeper/grpc_query_names.go
- x/rns/types/query.pb.go
Tested all query changes by making transactions and querying for them locally. All tests run.
> changed query.proto

- app/app.go
- x/storage/keeper/common_test.go
- x/storage/keeper/keeper.go
- x/storage/keeper/msg_server_buy_storage.go
- x/storage/keeper/msg_server_buy_storage_test.go
- x/storage/testutil/expected_keepers_mocks.go
- x/storage/types/expected_keepers.go
Can you guys look over the logic on this one, really want to be sure it's correct :)
> Storage prices from oracle

- x/storage/keeper/msg_server_buy_storage.go
- x/storage/keeper/msg_server_upgrade_storage.go
- x/storage/keeper/msg_server_upgrade_storage_test.go
- x/storage/keeper/utils.go
- x/storage/keeper/utils_test.go
added [GetStorageCost()](https://github.com/JackalLabs/canine-chain/blob/5b0d2116173736d6e5f7ccdedc96d445786555e4/x/storage/keeper/utils.go#L58) and [GetJklPrice()](https://github.com/JackalLabs/canine-chain/blob/5b0d2116173736d6e5f7ccdedc96d445786555e4/x/storage/keeper/utils.go#L76) to calculate storage cost
> refactoring storage price calculation progress update

- x/storage/keeper/msg_server_buy_storage.go
- x/storage/keeper/msg_server_buy_storage_test.go
> This will prevent user to run MsgBuyStorage if they already have an active plan

- x/filetree/keeper/marshalling_test.go
- x/filetree/keeper/msg_server_add_editors.go
- x/filetree/keeper/msg_server_add_viewers.go
- x/filetree/keeper/msg_server_post_file.go
- x/filetree/keeper/msg_server_remove_editors.go
- x/filetree/keeper/msg_server_remove_viewers.go
- x/filetree/keeper/msg_server_reset_editors.go
- x/filetree/keeper/msg_server_reset_viewers.go
- x/filetree/types/test_helpers.go
Successfully triggered JSON marshalling error in testing environment.
> Jkl 150 trigger marshalling error in tests

- x/filetree/keeper/msg_server_change_owner_test.go
Hi @nuggetnchill
Please review and merge. This is a major feature so please take your time with this--I've reviewed it extensively but please double check.
This is, ofcourse, lower priority than Danny's PR.
Thank you.
> change owner test done

- x/filetree/README.md
@karnthis I've updated the readMe following our discussion today. I've looked at this document extensively but please notify me if you need extra information or a correction on anything and I'll look into it.
@TheMarstonConnell Please merge this PR once @karnthis has approved.
Thank you.
> updated readme re: editors and viewers map

- x/storage/module_simulation.go
- x/storage/simulation/set_miner_ip.go
- x/storage/simulation/set_miner_totalspace.go
- x/storage/simulation/upgrade_storage.go
added simulation ops for set_provider_ip, set_provider_address and upgrade_strage.
> Implement storage simulation txs

- proto/canine_chain/rns/tx.proto
- x/rns/client/cli/tx.go
- x/rns/client/cli/tx_update.go
- x/rns/keeper/msg_server_basics_test.go
- x/rns/keeper/msg_server_buy.go
- x/rns/keeper/msg_server_buy_test.go
- x/rns/keeper/msg_server_register.go
- x/rns/keeper/msg_server_update.go
- x/rns/types/message_update.go
- x/rns/types/tx.pb.go
Fixing the issue where buying names would mangle the price & added the ability to update the data field of a name.
> Fix for Buying,  Added Update

- .github/workflows/release.yml
- app/upgrades/bouncybulldog/upgrades.go
- scripts/upgrade-test-mainnet.sh
- x/oracle/legacy/v2/store.go
- x/storage/legacy/paramUpgrade/store.go
- x/storage/legacy/v2/store.go
Last piece before the release candidate for main-net. Added better test scripts to ensure smooth upgrades and cleaned up the module versioning.
> 1.2.0 mainnet upgrade handlers

- scripts/test-node-dev.sh
- x/oracle/client/cli/tx_feeds.go
Made these additions so I can finish testing the chain to ensure all the encoding changes were good. Will approve amino-fixing after this PR is merged.
> update script and oracle 'update-feed tx'

- upgrades/gov-props/v1.2.0.md
Showcasing the new token printing process in the gov prop. I figure people will want to know about new inflation.
> docs: updating gov prop

- .github/workflows/release.yml
- go.mod
- go.sum
- scripts/test-provider.sh
- x/storage/keeper/msg_server_postproof.go
All post proof messages are free now like designed, had to fork Cosmos SDK, needs a better way.
> fix: PostProof messages are free

- x/filetree/README.md
- x/notifications/README.md
@karnthis for the filetree readMe update, it's best to voice chat for clarity.
what's changed for notifications: 
The filetree module is no longer responsible for setting users' notiCounters. This will have to be done via the notification module 'natively.' 
Happy to discuss everything in voice chat.
> Noti readme

- go.mod
- go.sum
We've seen some smaller providers on the network struggle to gain any rewards due to a high reward imbalance. This aims to fix that, allowing providers to run at zero costs to the network. They will of course still have hardware costs, but this will ensure the tokens allocated for gas stay neutral rather than declining when there is a low reward payout.
> Feat: Free PostContract message

- x/storage/keeper/attestation_test.go
- x/storage/keeper/attestations.go
- x/storage/keeper/msg_server_attest.go
- x/storage/keeper/msg_server_attest_test.go
- x/storage/keeper/rewards.go
- x/storage/types/errors.go
Test suite for on-chain hyper-scaling solution.
> Test: Hyper Scaling test-suite

- go.mod
- go.sum
Forgot to whitelist them in the SDK fork.
> Fix: Whitelisting Provider Messages

- x/storage/keeper/providers_test.go
Adding a small test suite that was left out but was used internally.
> Test: Provider Init Test Suite

- .gitignore
- go.mod
- go.sum
- scripts/start-provider.sh
- scripts/test-attest.sh
- x/storage/keeper/contract_killing.go
- x/storage/keeper/msg_server_report.go
- x/storage/keeper/rewards.go
Cleaned up some of the reporting system, and improved some test suites
> Cleanup: Reporting System

- x/jklmint/keeper/keeper.go
Porting https://github.com/JackalLabs/canine-chain/pull/371 to v3
> v3 Fix: Inflation displayed incorrectly in the API

- go.mod
- go.sum
- x/storage/keeper/msg_server_proofs_test.go
- x/storage/simulation/utils.go
- x/storage/types/file_deal.go
- x/storage/types/file_deal_test.go
- x/storage/utils/trees.go
Updated Merkle-go to enable json exporting & moved away from my fork.
> Deps: Updating merkle tree library

- x/filetree/client/cli/tx.go
- x/filetree/client/cli/tx_post_file_public.go
- x/storage/keeper/msg_server_cancel_contract.go
- x/storage/keeper/msg_server_contracts_test.go
- x/storage/keeper/msg_server_provider_claim_test.go
- x/storage/keeper/msg_server_providers_test.go
- x/storage/types/errors.go
Specifically targeting the 200 year files and their deletion.
> Better Errors

- go.mod
- go.sum
- x/filetree/types/codec.go
- x/storage/types/codec.go
> Ledger v3.x.x

- app/upgrades/v4/upgrade_test.go
- x/storage/keeper/grpc_query_price_check.go
> API: Query Price Check V4

- x/storage/keeper/grpc_query_price_check.go
Adjusting the price check to allow smaller units than 1gb
> API: Price Check Query

- x/storage/keeper/msg_server_buy_storage.go
- x/storage/types/expected_keepers.go
when you buy an account for someone else, it inits their account on chain.
> Init Account on buy

- go.mod
- go.sum
> v4 IBC-go Update

- scripts/slam.sh
- x/storage/client/cli/tx.go
- x/storage/client/cli/tx_post_file.go
> Slamming files script

- x/filetree/keeper/msg_server_add_editors.go
- x/filetree/keeper/msg_server_add_viewers.go
- x/filetree/keeper/msg_server_change_owner.go
- x/filetree/keeper/msg_server_delete_file.go
- x/filetree/keeper/msg_server_make_root.go
- x/filetree/keeper/msg_server_post_file.go
- x/filetree/keeper/msg_server_postkey.go
- x/filetree/keeper/msg_server_remove_editors.go
- x/filetree/keeper/msg_server_remove_viewers.go
- x/filetree/keeper/msg_server_reset_editors.go
- x/filetree/keeper/msg_server_reset_viewers.go
- x/filetree/types/events.go
- x/storage/keeper/msg_server_attest.go
- x/storage/keeper/msg_server_buy_storage.go
- x/storage/keeper/msg_server_file_delete.go
- x/storage/keeper/msg_server_init_provider.go
- x/storage/keeper/msg_server_post_file.go
- x/storage/keeper/msg_server_postproof.go
- x/storage/keeper/msg_server_provider_claim.go
- x/storage/keeper/msg_server_report.go
- x/storage/keeper/msg_server_set_provider_ip.go
- x/storage/keeper/msg_server_set_provider_keybase.go
- x/storage/keeper/msg_server_set_provider_totalspace.go
- x/storage/types/events.go
Adding common `jackal_message` event types for cross chain monitoring.
> Adding Common Events

- upgrades/gov-props/convert.py
> updating wasmvm

- x/storage/keeper/grpc_query_find_file.go
- x/storage/keeper/grpc_query_find_file_test.go
> fixing find files query

- x/storage/keeper/msg_server_post_file.go
- x/storage/types/events.go
some events never fire due to their placement with 200 year files
> moving storage events

- app/upgrades.go
- app/upgrades/v410beta/upgrades.go
> upgrade handler for v410

- x/filetree/keeper/msg_server_postkey.go
- x/storage/keeper/grpc_query_storage_stats.go
- x/storage/keeper/grpc_query_storage_stats_test.go
- x/storage/keeper/msg_server_post_file_test.go
Adding test for storage stats query & improving accuracy. Also removed a duplicate event call.
> Storage stats query cleaning

- x/notifications/keeper/blocks.go
- x/notifications/keeper/msg_server_block_senders.go
- x/notifications/keeper/msg_server_create_notifications.go
- x/notifications/keeper/msg_server_delete_notifications.go
- x/notifications/keeper/notifications.go
- x/notifications/types/events.go
- x/rns/keeper/bids.go
- x/rns/keeper/forsale.go
- x/rns/keeper/msg_server_accept_bid.go
- x/rns/keeper/msg_server_add_record.go
- x/rns/keeper/msg_server_bid.go
- x/rns/keeper/msg_server_buy.go
- x/rns/keeper/msg_server_cancel_bid.go
- x/rns/keeper/msg_server_del_record.go
- x/rns/keeper/msg_server_delist.go
- x/rns/keeper/msg_server_init.go
- x/rns/keeper/msg_server_list.go
- x/rns/keeper/msg_server_register.go
- x/rns/keeper/msg_server_transfer.go
- x/rns/keeper/msg_server_update.go
- x/rns/keeper/names.go
- x/rns/types/events.go
- x/storage/keeper/msg_server_file_delete.go
> RNS events

- app/upgrades.go
- app/upgrades/v420/upgrades.go
- go.mod
- go.sum
Gas stopped being free for proofs since v4, this fixes that
> fixing gas issues for providers

- cmd/canined/root.go
- cmd/canined/utils.go
simple utility function to generate addresses the way we do for POL
> address generation command

- x/rns/keeper/grpc_query_list_owned_names.go
- x/rns/keeper/register_test.go
Fixing list_owned_names route because of a custom pagination issue.
> RNS query fix

- app/upgrades.go
- app/upgrades/recover.go
- app/upgrades/v430/commont_test.go
- app/upgrades/v430/upgrade_test.go
- app/upgrades/v430/upgrades.go
Loading back in those other files and RNS tweaks
> Upgrade handler for v4.3.0

- scripts/upgrade-test.sh
- x/rns/keeper/grpc_query_list_owned_names.go
- x/rns/keeper/register_test.go
Doesn't show expired names in "my names" query now
> fixing rns expired results in query

- app/upgrades.go
- app/upgrades/v440/commont_test.go
- app/upgrades/v440/upgrade_test.go
- app/upgrades/v440/upgrades.go
- x/jklmint/keeper/mint.go
- x/jklmint/keeper/mint_test.go
- x/jklmint/module.go
- x/jklmint/utils/mint.go
There was a bug with the mint decrease module, to overcorrect it a bit, we can use a flat rate of inflation and switch it to a param change instead.
> switching mint module to flat rate

- app/upgrades/v440/upgrade_test.go
- app/upgrades/v440/upgrades.go
Finishing up the v4.4.0 upgrade handler
> v4.4.0 handler finalized

- app/upgrades.go
- app/upgrades/v450/commont_test.go
- app/upgrades/v450/upgrade_test.go
- app/upgrades/v450/upgrades.go
- x/storage/keeper/msg_server_post_file.go
Posting a file with an expiration was not sending tokens to the right account. Now it will, this also moves everything from the account back into the proper POL account.
> [BUG] POL not reflecting one-time buys 

- app/app.go
- wasmbinding/bindings/msg.go
- wasmbinding/filetree_messages.go
- wasmbinding/message_plugin.go
- wasmbinding/notifications_messages.go
- wasmbinding/storage_messages.go
- wasmbinding/wasm.go
These bindings enable smart contracts on canine-chain to utilize the chain modules directly, enabling the canine-chain<>mulberry<>solidity roundtrip!
> feat: web assembly bindings

- x/jklmint/types/params.go
- x/storage/types/params.go
fix some function names in comment
> chore: fix some function names in comment

- x/storage/keeper/grpc_query_find_file.go
- x/storage/keeper/rewards.go
minor improvements to rewards code
> faster rewards

- Makefile
when base go matched the toolchain version, the logic didn't handle this well.  This should be resolved with this patch.  as well as ensuring basic go pathing exists, and if not then we quit right away.  These were the two issues that came up post Makefile updates.
Brendan from Whispernode tested the Makefile changes, as they were affected from having their base go version match the wanted version.  These updates resolve the issue they had.
minor white space issues resolved.
> Makefile edge case fix for go version checking
